### PR TITLE
Swapped fast-json-stringify out for safe-stable-stringify

### LINKED ISSUE #104: Use safe-stable-stringify for perf and to support circular refs
The [winston](https://github.com/winstonjs/winston) package [updated it's stringification tool to `fast-safe-stringify`](https://github.com/winstonjs/logform/pull/35) a while back at Jun 11, 2018.

I introduced here: #57.  In it's PR I raised a this as a separate issue in [one comment](https://github.com/elastic/ecs-logging-nodejs/pull/65#issuecomment-815887931) with notes. Pulling those in here for easy read:

When I attempt to use req and res as part of the formatting meta data I get a new error:
Sample express controller method:

```ts
  public async logging(req: Request, res: Response) {
    logger.info("Log endpoint activated", {
      req,
      res,
      labels: {
        transactionId: res.locals?.transactionId,
      },
    });
  }
```

Result:
```
TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Socket'
| property '_writableState' -> object with constructor 'WritableState'
| property 'afterWriteTickInfo' -> object with constructor 'Object'
--- property 'stream' closes the circle

at JSON.stringify (<anonymous>)
at $main (eval at build (express-common/node_modules/fast-json-stringify/index.js:162:20), <anonymous>:345:51)
at Format.ecsStringifyTransform [as transform] (express-common/ecs-logging-nodejs/loggers/winston/index.js:149:19)
```

I tracked the cause down to:

```ts
function ecsStringifyTransform (info, opts) {
  info[MESSAGE] = stringify(info)
  return info
}
```

Where info contains `Symbol(splat)` which is `{req: IncomingMessage, res: ServerResponse, labels: Object}`, but there's a circular piece inside the req at several places because that's just Express. A little research showed me [Use fast-safe-stringify for perf and to support circular refs #35 in winstonjs/winston](https://github.com/winstonjs/logform/pull/35) changed their internal serialization agent to handle circular structure by moving to fast-safe-stringify. I checked the common helpers in this package and it looks like you're still using fast-json-stringify. Maybe that's somehow responsible for the difference?

A quick test swapping:

```ts
export const defaultOptions: LoggerOptions = {
  exitOnError: false,
  level: defaultLevel,
  format: format.combine(
    ecsFields({ convertReqRes: true }),
    new WinstonRedactFormatter({
      paths: ["http.request.headers.authorization"],
    }),
    // ecsStringify() // Bypass the ecsStringify
   format.json() // Use the winston standard json formatter
  ),
  transports: [new winston.transports.Console()],
};
```

Did indeed serial manage to output the correct format to the transporter:

```
{"labels":{"transactionId":"0c91f790-8083-44da-ac4d-91eedb51a130"},"message":"Log endpoint activated","@timestamp":"2021-04-08T14:49:59.724Z","log.level":"error","ecs":{"version":"1.6.0"},"http":{"version":"1.1","request":{"method":"GET","headers":{"host":"127.0.0.1:62723","accept-encoding":"gzip, deflate","user-agent":"node-superagent/3.8.3","authorization":"[REDACTED]","connection":"close"}},"response":{"status_code":200,"headers":{"x-powered-by":"Express","access-control-allow-origin":"*"}}},"url":{"full":"http://127.0.0.1:62723/logging-info","path":"/logging-info","domain":"127.0.0.1"},"client":{"address":"::ffff:127.0.0.1","ip":"::ffff:127.0.0.1","port":62724},"user_agent":{"original":"node-superagent/3.8.3"}}
```

### PR DESCRIPTION
**Pull request by lancegliser**
Fixes #104

### CODE REVIEW

**Comment by jonofoz** [comment]
@trentm @lancegliser This isn't going to work, as swapping out the libraries won't be as simple as changing the import.

Though unrelated, Winston's LogForm is using `safe-stable-stringify`; they _were_ using `fast-safe-stringify`, but [this was replaced as it was buggier and not as fast](https://github.com/winstonjs/logform/pull/98). We may want to consider using `safe-stable-stringify` instead here.

**Comment by lancegliser** [comment]
@jonofoz You were absolutely correct. I neglected to look in on how `fast-json-stringify` worked. There appears to be no need anymore of the strong object typing that was most of the serializer file when using `safe-stable-stringify`. I've tried to make adjustments to match.

**Comment by jonofoz** [comment]
@lancegliser When you get a chance, would you please re-check if you signed the contributor agreement, then run `/test` again?

**Comment by lancegliser** [comment]
Signed it a couple times already..

/test

**Comment by trentm** [comment]
> Signed it a couple times already..

The author on those commits is `Author: Lance Gliser <lance.gliser@torch.ai>`. Did you sign the CLA with that email address?

**Comment by trentm** [comment]
Also, I'm guessing the next hurdle for running tests will be having an Elastic employee (like me) review the code. I have this on my list but haven't yet had a chance to look closely.  (My head is slightly spinning at the number of JSON serialization libs out there. :)

**Comment by lancegliser** [comment]
Ahh that'd be me on my work computer. Didn't think that through and CLA'd my private emails! Thanks for pointing that out @trentm. Nice to see you, and looking forward to it!

**Comment by fidgi** [comment]
Hi, @lancegliser 
why not just using a more recent version of fast-json-stringify ?

It seems there was some improvments in it  : https://github.com/fastify/fast-json-stringify/commit/c9e363ea27960e6ee49e8f82e6eeed672a1a1077

**Comment by lancegliser** [comment]
That's wonderful news. Thanks @fidgi. I'll add a task in our system to try the updated version instead through `npm pack`.

**Comment by lancegliser** [comment]
@fidgi I used a local `npm pack` based off my fork to install into my project marked as 1.2.0 depending on  fastify/fast-json-stringify@3.0.3.

It shows the 3.x branch in my project now:

```shell
% npm ls fast-json-stringify
api@1.0.0 /Users/lancegliser/Projects/api
└─┬ @elastic/ecs-helpers@1.2.0
  └── fast-json-stringify@3.0.3
```

But serialize issue persists on API boot when it can't reach the database (just an easy use case for me to test against):
```shell
{"@timestamp":"2022-03-19T02:31:20.660Z","log.level":"debug","message":"Configuring application","ecs":{"version":"1.6.0"}}

{"@timestamp":"2022-03-19T02:31:20.772Z","log.level":"error","message":"onProcessUncaughtException:","ecs":{"version":"1.6.0"},"error":{"type":"TypeError","message":"Converting circular structure to JSON\n    --> starting at object with constructor 'IncomingMessage'\n    |     property 'req' -> object with constructor 'ClientRequest'\n    --- property 'res' closes the circle","stack_trace":"TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'IncomingMessage'\n    |     property 'req' -> object with constructor 'ClientRequest'\n    --- property 'res' closes the circle\n    at JSON.stringify (<anonymous>)\n    at $main (eval at build (/usr/local/mount/node_modules/fast-json-stringify/index.js:154:20), <anonymous>:383:51)\n    at Format.ecsTransform [as transform] (/usr/local/mount/node_modules/@elastic/ecs-winston-format/index.js:183:19)\n    at Format.transform (/usr/local/mount/node_modules/logform/combine.js:20:24)\n    at DerivedLogger._transform (/usr/local/mount/node_modules/winston/lib/winston/logger.js:313:29)\n    at DerivedLogger.Transform._read (/usr/local/mount/node_modules/readable-stream/lib/_stream_transform.js:177:10)\n    at DerivedLogger.Transform._write (/usr/local/mount/node_modules/readable-stream/lib/_stream_transform.js:164:83)\n    at doWrite (/usr/local/mount/node_modules/readable-stream/lib/_stream_writable.js:409:139)\n    at writeOrBuffer (/usr/local/mount/node_modules/readable-stream/lib/_stream_writable.js:398:5)\n    at DerivedLogger.Writable.write (/usr/local/mount/node_modules/readable-stream/lib/_stream_writable.js:307:11)"}}

{"@timestamp":"2022-03-19T02:31:20.790Z","log.level":"info","message":"Exiting with code: 1","ecs":{"version":"1.6.0"}}
```

It appears that solution won't work, but it does feel like a better direction than changing module. I may need to just put some handling in at every error point instead. For now, I'm going to abandon this approach.

**Pull request closed without merging**
