### PR TITLE
update branch to main

### PR DESCRIPTION
**Pull request by v1v**

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Review by bmorelli25 — APPROVED** [review]
Thanks for updating the docs! A lot of these links should be moved to attributes so we don't have to maintain them manually like this. I've opened   https://github.com/elastic/observability-docs/issues/1393 to address this.

**Comment by trentm** [comment]
The changes look good. 

However, I don't understand these test failures. For some reason, when running the Node v16 and v17 steps in Jenkins CI, inside the "node:16" and "node:17" docker containers, the current node version is **8.17.0**?!

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fecs-logging-nodejs-mbp/detail/PR-111/1/pipeline/103

```
[2021-12-16T17:42:24.946Z] + .ci/run-install.sh
...
[2021-12-16T17:42:24.946Z] + npm --prefix /var/lib/jenkins/workspace/js_ecs-logging-nodejs-mbp_PR-111/src/go.elastic.co/apm/ecs-logging-nodejs/helpers install
...
[2021-12-16T17:42:47.983Z] npm WARN notsup Unsupported engine for fast-json-stringify@2.7.12: wanted: {"node":">= 10.0.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
...
```

**Review by trentm — APPROVED** [review]

**Comment by v1v** [comment]
If I run the below command locally I cannot reproduce the error:

```
docker run --rm -ti -v $(pwd):/app node:16 /bin/bash
$ cd /app
$ .ci/run-install.sh
$ .ci/run-test.sh
```

Maybe some cached docker images are wrongly pointing to node:8 rather than node:16?

**Comment by v1v** [comment]
Unrelated test errors, I'll raise an issue to track those errors

**Pull request merged**
