### PR TITLE
fixes: #169 Add missing d.ts file in ecs-morgan-format

### LINKED ISSUE #169: [fix] index.d.ts missing in package.json of ecs-morgan-format
Hi, 
I tried using the @elastic/ecs-morgan-format in my ts project which gave following error,
`Cannot find module '@elastic/ecs-morgan-format' or its corresponding type declarations.`

After looking in the code I found `index.d.ts` is missing in the files property of [package.json](https://github.com/elastic/ecs-logging-nodejs/blob/23c6d6ec8e26e5396f44e4f79ae9b79504582bae/packages/ecs-morgan-format/package.json#L8). 

Creating PR to solve this small issue. ✌️

### PR DESCRIPTION
**Pull request by imsuvesh**
fixes #169
Added missing index.d.ts file in package.json files property so it will be added in next release.

### CODE REVIEW

**Comment by imsuvesh** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [6de2bc1](https://github.com/elastic/ecs-logging-nodejs/commit/6de2bc141e13e5f4efd8393c706e24a88a68bccc)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project



> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [6de2bc1](https://github.com/elastic/ecs-logging-nodejs/commit/6de2bc141e13e5f4efd8393c706e24a88a68bccc)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Signed

**Review by david-luna — APPROVED** [review]

**Comment by david-luna** [comment]
Thanks @imsuvesh for your contribution :)

**Review by trentm — APPROVED** [review]
Thanks!

**Comment by trentm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by trentm** [comment]
I'll get a release out with this today (https://github.com/elastic/ecs-logging-nodejs/pull/171).

**Pull request merged**
