### PR TITLE
Add TypeScript types for Pino logger

### PR DESCRIPTION
**Pull request by akselinurmio**
This PR adds TypeScript types for Pino logger.

### CODE REVIEW

**Comment by trentm** [comment]
@akselinurmio This looks great!  Please help me with some TypeScript types ignorance of mine. You've added `@types/pino` to "dependencies". This ends up increasing the install size of a user-installed `@elastic/ecs-pino-format` by 1MB because `@types/node` is large. Can `@types/*` be added to `devDependencies` instead and still have the same utility to users? I notice that https://github.com/DefinitelyTyped/DefinitelyTyped#npm suggests `npm install --save-dev ...` and that, for example, the fastify project puts its `@types/*` deps in `devDependencies`: https://github.com/fastify/fastify/blob/main/package.json#L120-L125

**Comment by akselinurmio** [comment]
@trentm I'm not entirely sure whether adding it to `devDependencies` works the same here, but I'll try to verify as soon as possible.

**Comment by trentm** [comment]
^ By the way, those test failures are not due to your changes, but rather due to the recent `elastic-apm-node@3.16.0` release. I am looking into it.

**Comment by trentm** [comment]
> ^ By the way, those test failures are not due to your changes, but rather due to the recent `elastic-apm-node@3.16.0` release. I am looking into it.

https://github.com/elastic/ecs-logging-nodejs/pull/83 fixes this.

@akselinurmio If you merge in changes from the master branch, tests should pass for your PR now.

**Comment by akselinurmio** [comment]
@trentm Based on a quick test, in this case the `@types/pino` needs to be located in the "dependencies" array. This is because when the package is published to NPM and used as a dependency by another package (say A), dependencies listed in `devDependencies` are not installed. This means that this package's function type is left with an `any` type as return type (see screenshot).

Screenshot 2021-06-16 at 10 46 40

**Comment by trentm** [comment]
(I'm still learning/playing here.)

I was reading https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html which suggests:

> If your types are generated by your source code, publish the types with your source code. Both TypeScript and JavaScript projects can generate types via --declaration.
>
> Otherwise, we recommend submitting the types to DefinitelyTyped, which will publish them to the @types organization on npm.

Looking briefly at the former (https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html provides some docs), that seems like a no-go:

```
[13:48:37 trentm@pink:~/el/ecs-logging-nodejs3/loggers/pino (git:master)]
% cat tsconfig.json
{
  "include": ["index.js"],
  "compilerOptions": {
    "allowJs": true,
    "declaration": true,
    "emitDeclarationOnly": true
  }
}
[13:48:40 trentm@pink:~/el/ecs-logging-nodejs3/loggers/pino (git:master)]
% tsc
node_modules/elastic-apm-node/index.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.

1 /// <reference types="node" />
                        ~~~~

node_modules/elastic-apm-node/index.d.ts:3:49 - error TS2307: Cannot find module 'http' or its corresponding type declarations.

3 import { IncomingMessage, ServerResponse } from 'http';
                                                  ~~~~~~


Found 2 errors.
```

* * *

The latter recommends submitting instead to DefinitelyTyped. I know many projects do that, but unfortunately the recommendations here don't mention *why* this recommendation?

- Is it to avoid this need for largish `@types/...` "dependencies"?
- Is it to separate package and types authors? (The main value being that a JS package author doesn't yet need to learn about TypeScript, DTS, et al.)

I see the value of shipping the types with the package: version mismatches, changes in API can get reflected in the types in the same change.

**Comment by trentm** [comment]
So here is a test of mine... which I **think** shows that `@types/pino` need not be installed by `npm install @elastic/ecs-pino-format` users to get types working. I'm not entirely confident, however.

## setup

I have a clean "q" directory for a node project. It has the latest `pino` and `@elastic/ecs-pino-format` installed:

```
[14:47:48 trentm@pink:~/tmp/q]
% cat package.json
{
  "name": "q",
  "version": "1.0.0",
  "main": "index.js",
  "license": "ISC",
  "dependencies": {
    "@elastic/ecs-pino-format": "^1.1.2",
    "pino": "^6.11.3"
  }
}
[14:47:56 trentm@pink:~/tmp/q]
% npm ls
q@1.0.0 /Users/trentm/tmp/q
├─┬ @elastic/ecs-pino-format@1.1.2
│ └─┬ @elastic/ecs-helpers@1.1.0
│   └─┬ fast-json-stringify@2.7.6
│     ├─┬ ajv@6.12.6
│     │ ├── fast-deep-equal@3.1.3
│     │ ├── fast-json-stable-stringify@2.1.0
│     │ ├── json-schema-traverse@0.4.1
│     │ └─┬ uri-js@4.4.1
│     │   └── punycode@2.1.1
│     ├── deepmerge@4.2.2
│     ├── rfdc@1.3.0
│     └── string-similarity@4.0.4
└─┬ pino@6.11.3
  ├── fast-redact@3.0.1
  ├── fast-safe-stringify@2.0.7
  ├── flatstr@1.0.12
  ├── pino-std-serializers@3.2.0
  ├── quick-format-unescaped@4.0.3
  └─┬ sonic-boom@1.4.1
    ├── atomic-sleep@1.0.0
    └── flatstr@1.0.12 deduped
```

I manually copied your index.d.ts into the ecs-pino-format install:

```
% ls node_modules/@elastic/ecs-pino-format/index.d.ts
node_modules/@elastic/ecs-pino-format/index.d.ts
```

which simulates adding your PR but *without `@types/pino` in "dependencies"*.


## types in VS Code for .js, .mjs, and .ts files

```
% cat foo.js
const ecsFormat = require('@elastic/ecs-pino-format')
const pino = require('pino')
const fmt = ecsFormat()
const log = pino(fmt)
log.info('Hello world')

% cat bar.mjs
import pino from 'pino'
import ecsFormat from '@elastic/ecs-pino-format'
const fmt = ecsFormat()
const log = pino(fmt)
log.info('hi')

% cat baz.ts
import pino from 'pino'
import ecsFormat from '@elastic/ecs-pino-format'
const fmt = ecsFormat()
const log = pino(fmt)
log.info('hi')
```

I created these files to test types in VS Code for each of CommonJS-style JS, ESM-style JS, and TypeScript files using these two packages.

### foo.js

VS Code knows the types for `fmt` and `log`:

Screen Shot 2021-06-23 at 2 52 21 PM
Screen Shot 2021-06-23 at 2 52 34 PM

### bar.mjs

Likewise, VS Code knows the types for `fmt` and `log`:

Screen Shot 2021-06-23 at 2 54 15 PM
Screen Shot 2021-06-23 at 2 54 27 PM

### baz.ts

VS Code knows (at least I think it does) the type for `fmt`, but **not** for `log`:

Screen Shot 2021-06-23 at 2 57 26 PM
Screen Shot 2021-06-23 at 2 57 37 PM
Screen Shot 2021-06-23 at 2 59 11 PM

I'm not sure if I'm showing my ignorance with TypeScript here to know why VS Code does not resolve the type for `pino`.


## conclusions

I'm not sure why my test shows a different result (no `any`) to your quick test comment above:

Screen Shot 2021-06-23 at 3 01 37 PM

**Comment by akselinurmio** [comment]
Hi @trentm, and sorry about the delay. And thank you for taking such a thorough look into this. I think we should go with pino's type package in the `devDependencies` as that seems to be working fine, based on your tests.

I have now made said changes to the PR. The CI seems not to be running tests on the PR (see screenshot below). If there's something for me to do, I'd be happy to help.

Screenshot 2021-07-23 at 13 11 30

**Review by trentm — APPROVED** [review]
LGTM.

(Also approving to see if that frees up CI checks automatically.)

**Comment by trentm** [comment]
@elastic/ecs-pino-format@1.3.0 finally published with this.

**Pull request merged**
